"""Database queries, one module per SPEC section.

Split from a single 2,468-line module. The re-exports below are the reason
every call site still reads ``queries.foo(...)`` after the split — the
package *is* the old module's public surface, and this is the one barrel
the backend keeps on purpose (the other is ``app.retrieval``).
"""

from __future__ import annotations

from app.db.queries._shared import (
    ACTIVE_STATUSES,
    IN_FLIGHT_STATUSES,
    REPO_STATUSES,
    SNAPSHOT_COLUMNS,
    SNAPSHOT_FROM,
    STRATEGIES,
    ChunkRow,
    FileRow,
)
from app.db.queries.compare import (
    commits_between,
    compare_dependencies,
    compare_files,
    compare_symbols,
    sibling_snapshots,
    snapshot_meta,
)
from app.db.queries.conversations import (
    append_turn,
    conversation_turns,
    create_conversation,
    delete_conversation,
    list_conversations,
    owned_conversation,
)
from app.db.queries.dependencies import (
    clear_repo_dependencies,
    declared_by_name,
    dependency_summary,
    dependency_uses,
    file_texts,
    has_dependencies,
    insert_dependencies,
    insert_dependency_uses,
    undeclared_dependencies,
    unused_dependencies,
)
from app.db.queries.graph_views import (
    entry_point_candidates,
    implementation_covered_by_file,
    module_edges,
    module_nodes,
    most_referenced_symbols,
    most_tested_files,
    public_api_symbols,
    tests_covering_file,
)
from app.db.queries.history import (
    clear_repo_history,
    commit_history,
    has_history,
    insert_commit_files,
    insert_commits,
)
from app.db.queries.incremental import (
    copy_chunks,
    file_digests,
    reusable_snapshot,
    set_snapshot_embedding_model,
)
from app.db.queries.ingest import (
    claim_snapshot,
    clear_repo_content,
    count_active_ingests_for_user,
    count_chunks,
    fail_repo,
    finalize_repo,
    get_file,
    insert_chunks,
    insert_files,
    resolve_snapshot_id,
    set_repo_clone_info,
    set_repo_progress,
    set_repo_status,
    start_ingest,
    sweep_expired_leases,
    sweep_zombie_repos,
    touch_heartbeat,
)
from app.db.queries.overviews import (
    claim_overview,
    clear_failed_overview,
    fail_overview,
    finish_overview,
    get_overview,
    readme_sections,
)
from app.db.queries.sharing import (
    create_shared_answer,
    delete_shared_answer,
    get_shared_answer,
)
from app.db.queries.sources import (
    create_snapshot,
    find_ready_snapshot,
    get_or_create_source,
    get_owned_repo,
    get_repo,
    list_repos,
    newest_snapshot_for_source,
    source_of,
    supersede_snapshot,
)
from app.db.queries.symbols import (
    backfill_chunk_symbol_ids,
    clear_repo_graph,
    implementation_callers,
    insert_edges,
    insert_symbols,
    resolve_symbol_id,
    symbol_id_map,
)
from app.db.queries.trace import (
    find_symbol,
    symbol_seed_ids,
    trace_graph,
)
from app.db.queries.users import (
    adopt_bootstrap_user,
    get_user,
    link_user_repo,
    resolve_owner_id,
    upsert_user,
)

__all__ = [
    "ACTIVE_STATUSES",
    "ChunkRow",
    "FileRow",
    "IN_FLIGHT_STATUSES",
    "REPO_STATUSES",
    "SNAPSHOT_COLUMNS",
    "SNAPSHOT_FROM",
    "STRATEGIES",
    "adopt_bootstrap_user",
    "append_turn",
    "backfill_chunk_symbol_ids",
    "claim_overview",
    "claim_snapshot",
    "clear_failed_overview",
    "clear_repo_content",
    "clear_repo_dependencies",
    "clear_repo_graph",
    "clear_repo_history",
    "commit_history",
    "commits_between",
    "compare_dependencies",
    "compare_files",
    "compare_symbols",
    "conversation_turns",
    "copy_chunks",
    "count_active_ingests_for_user",
    "count_chunks",
    "create_conversation",
    "create_shared_answer",
    "create_snapshot",
    "declared_by_name",
    "delete_conversation",
    "delete_shared_answer",
    "dependency_summary",
    "dependency_uses",
    "entry_point_candidates",
    "fail_overview",
    "fail_repo",
    "file_digests",
    "file_texts",
    "finalize_repo",
    "find_ready_snapshot",
    "find_symbol",
    "finish_overview",
    "get_file",
    "get_or_create_source",
    "get_overview",
    "get_owned_repo",
    "get_repo",
    "get_shared_answer",
    "get_user",
    "has_dependencies",
    "has_history",
    "implementation_callers",
    "implementation_covered_by_file",
    "insert_chunks",
    "insert_commit_files",
    "insert_commits",
    "insert_dependencies",
    "insert_dependency_uses",
    "insert_edges",
    "insert_files",
    "insert_symbols",
    "link_user_repo",
    "list_conversations",
    "list_repos",
    "module_edges",
    "module_nodes",
    "most_referenced_symbols",
    "most_tested_files",
    "newest_snapshot_for_source",
    "owned_conversation",
    "public_api_symbols",
    "readme_sections",
    "resolve_owner_id",
    "resolve_snapshot_id",
    "resolve_symbol_id",
    "reusable_snapshot",
    "set_repo_clone_info",
    "set_repo_progress",
    "set_repo_status",
    "set_snapshot_embedding_model",
    "sibling_snapshots",
    "snapshot_meta",
    "source_of",
    "start_ingest",
    "supersede_snapshot",
    "sweep_expired_leases",
    "sweep_zombie_repos",
    "symbol_id_map",
    "symbol_seed_ids",
    "tests_covering_file",
    "touch_heartbeat",
    "trace_graph",
    "undeclared_dependencies",
    "unused_dependencies",
    "upsert_user",
]
